spring:
    # 激活的配置文件
    profiles:
      active: dev
    # 异常处理配置 无需修改
    mvc:
      throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
    #servlet配置
    servlet:
      multipart:
        # 允许的最大文件大小
        max-file-size: 50MB
        # 允许的最大请求大小
        max-request-size: 50MB
    # 数据源配置
    datasource:
      # 连接池类型: Druid
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  error:
    whitelabel:
      # 关闭默认whitelabel
      enabled: false

#MyBatis框架配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yeliheng.blogsystem.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# token 配置
token:
  # 令牌有效期(默认30分钟)
  expireTime: 30
  # 令牌密钥
  secret: yeliheng123
  # 令牌请求头
  header: Authorization
# 系统设置
system:
  # 允许注册？
  allow-register: false
  file-system:
    # 允许最大的文件名长度
    max-filename-length: 100
    # 允许的文件大小(M)
    max-file-size: 5