spring:
    # 激活的配置文件
    profiles:
      active: dev
    # 异常处理配置 无需修改
    mvc:
      throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
    #servlet配置
    servlet:
      multipart:
        # 允许的最大文件大小
        max-file-size: 50MB
        # 允许的最大请求大小
        max-request-size: 50MB
    # 数据源配置
    datasource:
      # 连接池类型: Druid
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
server:
  error:
    whitelabel:
      # 关闭默认whitelabel
      enabled: false
  tomcat:
    mbeanregistry:
      enabled: true
# 指标监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
# springdoc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#MyBatis框架配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yeliheng.blogsystem.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# token 配置
token:
  # 令牌有效期(默认30分钟)
  expireTime: 30
  # 令牌密钥
  secret: yeliheng123
  # 令牌请求头
  header: Authorization
#验证码配置
kaptcha:
  # 高度
  height: 50
  # 宽度
  width: 200
  # 内容
  content:
    # 长度
    length: 4
    # 从以下字母生成
    source: abcdefghjklmnopqrstuvwxyz23456789
    # 空格
    space: 2
  # 字体
  font:
    # 颜色
    color: black
    # 字体
    name: Arial
    # 字号
    size: 40
  # 背景颜色(渐变)
  background-color:
    from: lightGray
    to: white
  # 边框
  border:
    enabled: true
    # 边框颜色
    color: black
    # 粗细
    thickness: 1
# 系统设置
system:
  # 允许注册？
  allow-register: false
  # 验证码开关
  captcha-enabled: false